#Control Table Constants
MODEL_NUMBER = 0
VERSION_OF_FIRMWARE = 2
ID = 3
BAUD_RATE = 4
RETURN_DELAY_TIME = 5
CW_ANGLE_LIMIT = 6
CCW_ANGLE_LIMIT = 8
HIGHEST_TEMPERATURE = 11
LOWEST_VOLTAGE = 12
HIGHEST_VOLTAGE = 13
MAX_TORQUE = 14
STATUS_RETURN_LEVEL = 16
ALARM_LED = 17
ALARM_SHUTDOWN = 18
DOWN_CALIBRATION = 20
UP_CALIBRATION = 22
TORQUE_ENABLE = 24
LED = 25
CW_COMPLIANCE_MARGIN = 26
CCW_COMPLIANCE_MARGIN = 27
CW_COMPLIANCE_SLOPE = 28
CCW_COMPLIANCE_SLOPE = 29
GOAL_POSITION = 30
MOVING_SPEED = 32
TORQUE_LIMIT = 34
PRESENT_POSITION = 36
PRESENT_SPEED = 38
PRESENT_LOAD = 40
PRESENT_VOLTAGE = 42
PRESENT_TEMPERATURE = 43
REGISTERED_INSTRUCTION = 44
MOVING = 46
LOCK = 47
PUNCH = 48

#Instruction Constants
PING = 1
READ_DATA = 2
WRITE_DATA = 3
REG_WRITE = 4
ACTION = 5
RESET = 6
SYNC_WRITE = 0x83

#Other Constants
BROADCASTING_ID = 0xFE
