/* Auto-generated by genmsg_cpp for file /home/dave/ros/clam/dynamixel_hardware_interface/msg/MotorStateList.msg */
#ifndef DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_MOTORSTATELIST_H
#define DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_MOTORSTATELIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "dynamixel_hardware_interface/MotorState.h"

namespace dynamixel_hardware_interface
{
template <class ContainerAllocator>
struct MotorStateList_ {
  typedef MotorStateList_<ContainerAllocator> Type;

  MotorStateList_()
  : motor_states()
  {
  }

  MotorStateList_(const ContainerAllocator& _alloc)
  : motor_states(_alloc)
  {
  }

  typedef std::vector< ::dynamixel_hardware_interface::MotorState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dynamixel_hardware_interface::MotorState_<ContainerAllocator> >::other >  _motor_states_type;
  std::vector< ::dynamixel_hardware_interface::MotorState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::dynamixel_hardware_interface::MotorState_<ContainerAllocator> >::other >  motor_states;


  typedef boost::shared_ptr< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorStateList
typedef  ::dynamixel_hardware_interface::MotorStateList_<std::allocator<void> > MotorStateList;

typedef boost::shared_ptr< ::dynamixel_hardware_interface::MotorStateList> MotorStateListPtr;
typedef boost::shared_ptr< ::dynamixel_hardware_interface::MotorStateList const> MotorStateListConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace dynamixel_hardware_interface

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a2b6b94d09777cc1efb8ff09e1e054af";
  }

  static const char* value(const  ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa2b6b94d09777cc1ULL;
  static const uint64_t static_value2 = 0xefb8ff09e1e054afULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dynamixel_hardware_interface/MotorStateList";
  }

  static const char* value(const  ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MotorState[] motor_states\n\
\n\
================================================================================\n\
MSG: dynamixel_hardware_interface/MotorState\n\
# all values are in encoder units unless otherwise specified\n\
\n\
float64 timestamp       # motor state is at this time\n\
\n\
int32 id                # motor id\n\
int32 target_position   # commanded position\n\
int32 target_velocity   # commanded velocity\n\
int32 position          # current position\n\
int32 velocity          # current velocity\n\
int32 torque_limit      # current torque limit\n\
int32 load              # current load - ratio of applied torque over maximum torque\n\
bool  moving            # whether the motor is currently in motion\n\
\n\
int32 voltage           # current voltage (V * 10)\n\
int32 temperature       # current temperature (degrees Celsius)\n\
\n\
\n\
";
  }

  static const char* value(const  ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.motor_states);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorStateList_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::dynamixel_hardware_interface::MotorStateList_<ContainerAllocator> & v) 
  {
    s << indent << "motor_states[]" << std::endl;
    for (size_t i = 0; i < v.motor_states.size(); ++i)
    {
      s << indent << "  motor_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::dynamixel_hardware_interface::MotorState_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_states[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_MOTORSTATELIST_H

