arm:
  kinematics_solver: clam_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 1
gripper_group:
  kinematics_solver: clam_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 12
  kinematics_solver_timeout: 34
  kinematics_solver_attempts: 56