#goal definition
float64 GRIPPER_OPEN = 0.0
float64 GRIPPER_CLOSE = 1.0
float64 position                 # 0 is open, 1 or any other number is closed
float64 max_effort
bool double_close # Close up to a point then re-open then close again, better for grasping with uncertainty
---
#result
float64 position  # The current gripper gap size (in meters)
float64 effort    # The current effort exerted (in Newtons)
bool stalled      # True iff the gripper is exerting max effort and not moving
bool reached_goal # True iff the gripper position has reached the commanded setpoint
---
#feedback
float64 position  # The current gripper gap size (in meters)
float64 effort    # The current effort exerted (in Newtons)
bool stalled      # True iff the gripper is exerting max effort and not moving
bool reached_goal # True iff the gripper position has reached the commanded setpoint
