; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude ClamArmGoal.msg.html

(cl:defclass <ClamArmGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:string
    :initform ""))
)

(cl:defclass ClamArmGoal (<ClamArmGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ClamArmGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ClamArmGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<ClamArmGoal> is deprecated: use clam_block_manipulation-msg:ClamArmGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <ClamArmGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader clam_block_manipulation-msg:command-val is deprecated.  Use clam_block_manipulation-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ClamArmGoal>) ostream)
  "Serializes a message object of type '<ClamArmGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'command))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'command))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ClamArmGoal>) istream)
  "Deserializes a message object of type '<ClamArmGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'command) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ClamArmGoal>)))
  "Returns string type for a message object of type '<ClamArmGoal>"
  "clam_block_manipulation/ClamArmGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ClamArmGoal)))
  "Returns string type for a message object of type 'ClamArmGoal"
  "clam_block_manipulation/ClamArmGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ClamArmGoal>)))
  "Returns md5sum for a message object of type '<ClamArmGoal>"
  "cba5e21e920a3a2b7b375cb65b64cdea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ClamArmGoal)))
  "Returns md5sum for a message object of type 'ClamArmGoal"
  "cba5e21e920a3a2b7b375cb65b64cdea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ClamArmGoal>)))
  "Returns full string definition for message of type '<ClamArmGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ClamArmGoal)))
  "Returns full string definition for message of type 'ClamArmGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ClamArmGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'command))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ClamArmGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ClamArmGoal
    (cl:cons ':command (command msg))
))
