; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude ClamArmFeedback.msg.html

(cl:defclass <ClamArmFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ClamArmFeedback (<ClamArmFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ClamArmFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ClamArmFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<ClamArmFeedback> is deprecated: use clam_block_manipulation-msg:ClamArmFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ClamArmFeedback>) ostream)
  "Serializes a message object of type '<ClamArmFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ClamArmFeedback>) istream)
  "Deserializes a message object of type '<ClamArmFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ClamArmFeedback>)))
  "Returns string type for a message object of type '<ClamArmFeedback>"
  "clam_block_manipulation/ClamArmFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ClamArmFeedback)))
  "Returns string type for a message object of type 'ClamArmFeedback"
  "clam_block_manipulation/ClamArmFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ClamArmFeedback>)))
  "Returns md5sum for a message object of type '<ClamArmFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ClamArmFeedback)))
  "Returns md5sum for a message object of type 'ClamArmFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ClamArmFeedback>)))
  "Returns full string definition for message of type '<ClamArmFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ClamArmFeedback)))
  "Returns full string definition for message of type 'ClamArmFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ClamArmFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ClamArmFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ClamArmFeedback
))
