; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude InteractiveBlockManipulationFeedback.msg.html

(cl:defclass <InteractiveBlockManipulationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass InteractiveBlockManipulationFeedback (<InteractiveBlockManipulationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <InteractiveBlockManipulationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'InteractiveBlockManipulationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<InteractiveBlockManipulationFeedback> is deprecated: use clam_block_manipulation-msg:InteractiveBlockManipulationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <InteractiveBlockManipulationFeedback>) ostream)
  "Serializes a message object of type '<InteractiveBlockManipulationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <InteractiveBlockManipulationFeedback>) istream)
  "Deserializes a message object of type '<InteractiveBlockManipulationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<InteractiveBlockManipulationFeedback>)))
  "Returns string type for a message object of type '<InteractiveBlockManipulationFeedback>"
  "clam_block_manipulation/InteractiveBlockManipulationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'InteractiveBlockManipulationFeedback)))
  "Returns string type for a message object of type 'InteractiveBlockManipulationFeedback"
  "clam_block_manipulation/InteractiveBlockManipulationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<InteractiveBlockManipulationFeedback>)))
  "Returns md5sum for a message object of type '<InteractiveBlockManipulationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'InteractiveBlockManipulationFeedback)))
  "Returns md5sum for a message object of type 'InteractiveBlockManipulationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<InteractiveBlockManipulationFeedback>)))
  "Returns full string definition for message of type '<InteractiveBlockManipulationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'InteractiveBlockManipulationFeedback)))
  "Returns full string definition for message of type 'InteractiveBlockManipulationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <InteractiveBlockManipulationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <InteractiveBlockManipulationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'InteractiveBlockManipulationFeedback
))
