; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude InteractiveBlockManipulationResult.msg.html

(cl:defclass <InteractiveBlockManipulationResult> (roslisp-msg-protocol:ros-message)
  ((pickup_pose
    :reader pickup_pose
    :initarg :pickup_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (place_pose
    :reader place_pose
    :initarg :place_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass InteractiveBlockManipulationResult (<InteractiveBlockManipulationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <InteractiveBlockManipulationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'InteractiveBlockManipulationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<InteractiveBlockManipulationResult> is deprecated: use clam_block_manipulation-msg:InteractiveBlockManipulationResult instead.")))

(cl:ensure-generic-function 'pickup_pose-val :lambda-list '(m))
(cl:defmethod pickup_pose-val ((m <InteractiveBlockManipulationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader clam_block_manipulation-msg:pickup_pose-val is deprecated.  Use clam_block_manipulation-msg:pickup_pose instead.")
  (pickup_pose m))

(cl:ensure-generic-function 'place_pose-val :lambda-list '(m))
(cl:defmethod place_pose-val ((m <InteractiveBlockManipulationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader clam_block_manipulation-msg:place_pose-val is deprecated.  Use clam_block_manipulation-msg:place_pose instead.")
  (place_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <InteractiveBlockManipulationResult>) ostream)
  "Serializes a message object of type '<InteractiveBlockManipulationResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pickup_pose) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'place_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <InteractiveBlockManipulationResult>) istream)
  "Deserializes a message object of type '<InteractiveBlockManipulationResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pickup_pose) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'place_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<InteractiveBlockManipulationResult>)))
  "Returns string type for a message object of type '<InteractiveBlockManipulationResult>"
  "clam_block_manipulation/InteractiveBlockManipulationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'InteractiveBlockManipulationResult)))
  "Returns string type for a message object of type 'InteractiveBlockManipulationResult"
  "clam_block_manipulation/InteractiveBlockManipulationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<InteractiveBlockManipulationResult>)))
  "Returns md5sum for a message object of type '<InteractiveBlockManipulationResult>"
  "3fec3f60e60c18ca7b67a7513b211e95")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'InteractiveBlockManipulationResult)))
  "Returns md5sum for a message object of type 'InteractiveBlockManipulationResult"
  "3fec3f60e60c18ca7b67a7513b211e95")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<InteractiveBlockManipulationResult>)))
  "Returns full string definition for message of type '<InteractiveBlockManipulationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%geometry_msgs/Pose pickup_pose~%geometry_msgs/Pose place_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'InteractiveBlockManipulationResult)))
  "Returns full string definition for message of type 'InteractiveBlockManipulationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%geometry_msgs/Pose pickup_pose~%geometry_msgs/Pose place_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <InteractiveBlockManipulationResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pickup_pose))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'place_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <InteractiveBlockManipulationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'InteractiveBlockManipulationResult
    (cl:cons ':pickup_pose (pickup_pose msg))
    (cl:cons ':place_pose (place_pose msg))
))
