; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude ResetArmFeedback.msg.html

(cl:defclass <ResetArmFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ResetArmFeedback (<ResetArmFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ResetArmFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ResetArmFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<ResetArmFeedback> is deprecated: use clam_block_manipulation-msg:ResetArmFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ResetArmFeedback>) ostream)
  "Serializes a message object of type '<ResetArmFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ResetArmFeedback>) istream)
  "Deserializes a message object of type '<ResetArmFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ResetArmFeedback>)))
  "Returns string type for a message object of type '<ResetArmFeedback>"
  "clam_block_manipulation/ResetArmFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ResetArmFeedback)))
  "Returns string type for a message object of type 'ResetArmFeedback"
  "clam_block_manipulation/ResetArmFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ResetArmFeedback>)))
  "Returns md5sum for a message object of type '<ResetArmFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ResetArmFeedback)))
  "Returns md5sum for a message object of type 'ResetArmFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ResetArmFeedback>)))
  "Returns full string definition for message of type '<ResetArmFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ResetArmFeedback)))
  "Returns full string definition for message of type 'ResetArmFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ResetArmFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ResetArmFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ResetArmFeedback
))
