; Auto-generated. Do not edit!


(cl:in-package clam_block_manipulation-msg)


;//! \htmlinclude ResetArmGoal.msg.html

(cl:defclass <ResetArmGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ResetArmGoal (<ResetArmGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ResetArmGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ResetArmGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name clam_block_manipulation-msg:<ResetArmGoal> is deprecated: use clam_block_manipulation-msg:ResetArmGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ResetArmGoal>) ostream)
  "Serializes a message object of type '<ResetArmGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ResetArmGoal>) istream)
  "Deserializes a message object of type '<ResetArmGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ResetArmGoal>)))
  "Returns string type for a message object of type '<ResetArmGoal>"
  "clam_block_manipulation/ResetArmGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ResetArmGoal)))
  "Returns string type for a message object of type 'ResetArmGoal"
  "clam_block_manipulation/ResetArmGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ResetArmGoal>)))
  "Returns md5sum for a message object of type '<ResetArmGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ResetArmGoal)))
  "Returns md5sum for a message object of type 'ResetArmGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ResetArmGoal>)))
  "Returns full string definition for message of type '<ResetArmGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ResetArmGoal)))
  "Returns full string definition for message of type 'ResetArmGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ResetArmGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ResetArmGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ResetArmGoal
))
