/* Auto-generated by genmsg_cpp for file /home/dave/ros/clam/clam_block_manipulation/msg/ClamArmGoal.msg */
#ifndef CLAM_BLOCK_MANIPULATION_MESSAGE_CLAMARMGOAL_H
#define CLAM_BLOCK_MANIPULATION_MESSAGE_CLAMARMGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace clam_block_manipulation
{
template <class ContainerAllocator>
struct ClamArmGoal_ {
  typedef ClamArmGoal_<ContainerAllocator> Type;

  ClamArmGoal_()
  : command()
  {
  }

  ClamArmGoal_(const ContainerAllocator& _alloc)
  : command(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;


  typedef boost::shared_ptr< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ClamArmGoal
typedef  ::clam_block_manipulation::ClamArmGoal_<std::allocator<void> > ClamArmGoal;

typedef boost::shared_ptr< ::clam_block_manipulation::ClamArmGoal> ClamArmGoalPtr;
typedef boost::shared_ptr< ::clam_block_manipulation::ClamArmGoal const> ClamArmGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clam_block_manipulation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const  ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clam_block_manipulation/ClamArmGoal";
  }

  static const char* value(const  ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string command\n\
\n\
";
  }

  static const char* value(const  ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ClamArmGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clam_block_manipulation::ClamArmGoal_<ContainerAllocator> & v) 
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLAM_BLOCK_MANIPULATION_MESSAGE_CLAMARMGOAL_H

