/* Auto-generated by genmsg_cpp for file /home/dave/ros/clam/clam_block_manipulation/msg/PickAndPlaceResult.msg */
#ifndef CLAM_BLOCK_MANIPULATION_MESSAGE_PICKANDPLACERESULT_H
#define CLAM_BLOCK_MANIPULATION_MESSAGE_PICKANDPLACERESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace clam_block_manipulation
{
template <class ContainerAllocator>
struct PickAndPlaceResult_ {
  typedef PickAndPlaceResult_<ContainerAllocator> Type;

  PickAndPlaceResult_()
  {
  }

  PickAndPlaceResult_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PickAndPlaceResult
typedef  ::clam_block_manipulation::PickAndPlaceResult_<std::allocator<void> > PickAndPlaceResult;

typedef boost::shared_ptr< ::clam_block_manipulation::PickAndPlaceResult> PickAndPlaceResultPtr;
typedef boost::shared_ptr< ::clam_block_manipulation::PickAndPlaceResult const> PickAndPlaceResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace clam_block_manipulation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "clam_block_manipulation/PickAndPlaceResult";
  }

  static const char* value(const  ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
\n\
";
  }

  static const char* value(const  ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PickAndPlaceResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::clam_block_manipulation::PickAndPlaceResult_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // CLAM_BLOCK_MANIPULATION_MESSAGE_PICKANDPLACERESULT_H

