/* Auto-generated by genmsg_cpp for file /home/shenas/rave_experimental/msg/BodyStatus.msg */
#ifndef RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUS_H
#define RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace rave_experimental
{
template <class ContainerAllocator>
struct BodyStatus_ : public ros::Message
{
  typedef BodyStatus_<ContainerAllocator> Type;

  BodyStatus_()
  : object_id()
  , picked_up(false)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , errno(0.0)
  {
  }

  BodyStatus_(const ContainerAllocator& _alloc)
  : object_id(_alloc)
  , picked_up(false)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , errno(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  object_id;

  typedef uint8_t _picked_up_type;
  uint8_t picked_up;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _errno_type;
  float errno;


private:
  static const char* __s_getDataType_() { return "rave_experimental/BodyStatus"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "9d67177aea4c214587c878f7ce226d1f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string object_id\n\
bool picked_up\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 errno\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, object_id);
    ros::serialization::serialize(stream, picked_up);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, z);
    ros::serialization::serialize(stream, errno);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, object_id);
    ros::serialization::deserialize(stream, picked_up);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, z);
    ros::serialization::deserialize(stream, errno);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(object_id);
    size += ros::serialization::serializationLength(picked_up);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(z);
    size += ros::serialization::serializationLength(errno);
    return size;
  }

  typedef boost::shared_ptr< ::rave_experimental::BodyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rave_experimental::BodyStatus_<ContainerAllocator>  const> ConstPtr;
}; // struct BodyStatus
typedef  ::rave_experimental::BodyStatus_<std::allocator<void> > BodyStatus;

typedef boost::shared_ptr< ::rave_experimental::BodyStatus> BodyStatusPtr;
typedef boost::shared_ptr< ::rave_experimental::BodyStatus const> BodyStatusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rave_experimental::BodyStatus_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rave_experimental::BodyStatus_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rave_experimental

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::rave_experimental::BodyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9d67177aea4c214587c878f7ce226d1f";
  }

  static const char* value(const  ::rave_experimental::BodyStatus_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9d67177aea4c2145ULL;
  static const uint64_t static_value2 = 0x87c878f7ce226d1fULL;
};

template<class ContainerAllocator>
struct DataType< ::rave_experimental::BodyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rave_experimental/BodyStatus";
  }

  static const char* value(const  ::rave_experimental::BodyStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rave_experimental::BodyStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string object_id\n\
bool picked_up\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 errno\n\
\n\
";
  }

  static const char* value(const  ::rave_experimental::BodyStatus_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rave_experimental::BodyStatus_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_id);
    stream.next(m.picked_up);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.errno);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BodyStatus_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rave_experimental::BodyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rave_experimental::BodyStatus_<ContainerAllocator> & v) 
  {
    s << indent << "object_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_id);
    s << indent << "picked_up: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.picked_up);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "errno: ";
    Printer<float>::stream(s, indent + "  ", v.errno);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUS_H

