/* Auto-generated by genmsg_cpp for file /home/shenas/rave_experimental/msg/BodyStatusRequest.msg */
#ifndef RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUSREQUEST_H
#define RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUSREQUEST_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace rave_experimental
{
template <class ContainerAllocator>
struct BodyStatusRequest_ : public ros::Message
{
  typedef BodyStatusRequest_<ContainerAllocator> Type;

  BodyStatusRequest_()
  : object_id()
  {
  }

  BodyStatusRequest_(const ContainerAllocator& _alloc)
  : object_id(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  object_id;


private:
  static const char* __s_getDataType_() { return "rave_experimental/BodyStatusRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d552cd960e0a22b19c9db18033cea0eb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string object_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, object_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, object_id);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(object_id);
    return size;
  }

  typedef boost::shared_ptr< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rave_experimental::BodyStatusRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct BodyStatusRequest
typedef  ::rave_experimental::BodyStatusRequest_<std::allocator<void> > BodyStatusRequest;

typedef boost::shared_ptr< ::rave_experimental::BodyStatusRequest> BodyStatusRequestPtr;
typedef boost::shared_ptr< ::rave_experimental::BodyStatusRequest const> BodyStatusRequestConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rave_experimental::BodyStatusRequest_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rave_experimental

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d552cd960e0a22b19c9db18033cea0eb";
  }

  static const char* value(const  ::rave_experimental::BodyStatusRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd552cd960e0a22b1ULL;
  static const uint64_t static_value2 = 0x9c9db18033cea0ebULL;
};

template<class ContainerAllocator>
struct DataType< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rave_experimental/BodyStatusRequest";
  }

  static const char* value(const  ::rave_experimental::BodyStatusRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string object_id\n\
\n\
";
  }

  static const char* value(const  ::rave_experimental::BodyStatusRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BodyStatusRequest_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rave_experimental::BodyStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rave_experimental::BodyStatusRequest_<ContainerAllocator> & v) 
  {
    s << indent << "object_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVE_EXPERIMENTAL_MESSAGE_BODYSTATUSREQUEST_H

