/* Auto-generated by genmsg_cpp for file /home/shenas/rave_experimental/msg/PutCommand.msg */
#ifndef RAVE_EXPERIMENTAL_MESSAGE_PUTCOMMAND_H
#define RAVE_EXPERIMENTAL_MESSAGE_PUTCOMMAND_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace rave_experimental
{
template <class ContainerAllocator>
struct PutCommand_ : public ros::Message
{
  typedef PutCommand_<ContainerAllocator> Type;

  PutCommand_()
  : object_id()
  , x_offset(0.0)
  , y_offset(0.0)
  , z_offset(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , release(false)
  {
  }

  PutCommand_(const ContainerAllocator& _alloc)
  : object_id(_alloc)
  , x_offset(0.0)
  , y_offset(0.0)
  , z_offset(0.0)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , release(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  object_id;

  typedef float _x_offset_type;
  float x_offset;

  typedef float _y_offset_type;
  float y_offset;

  typedef float _z_offset_type;
  float z_offset;

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;

  typedef uint8_t _release_type;
  uint8_t release;


private:
  static const char* __s_getDataType_() { return "rave_experimental/PutCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "f555af83d35595cf42f4aeb704d9cd78"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string object_id\n\
float32 x_offset\n\
float32 y_offset\n\
float32 z_offset\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
bool release\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, object_id);
    ros::serialization::serialize(stream, x_offset);
    ros::serialization::serialize(stream, y_offset);
    ros::serialization::serialize(stream, z_offset);
    ros::serialization::serialize(stream, roll);
    ros::serialization::serialize(stream, pitch);
    ros::serialization::serialize(stream, yaw);
    ros::serialization::serialize(stream, release);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, object_id);
    ros::serialization::deserialize(stream, x_offset);
    ros::serialization::deserialize(stream, y_offset);
    ros::serialization::deserialize(stream, z_offset);
    ros::serialization::deserialize(stream, roll);
    ros::serialization::deserialize(stream, pitch);
    ros::serialization::deserialize(stream, yaw);
    ros::serialization::deserialize(stream, release);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(object_id);
    size += ros::serialization::serializationLength(x_offset);
    size += ros::serialization::serializationLength(y_offset);
    size += ros::serialization::serializationLength(z_offset);
    size += ros::serialization::serializationLength(roll);
    size += ros::serialization::serializationLength(pitch);
    size += ros::serialization::serializationLength(yaw);
    size += ros::serialization::serializationLength(release);
    return size;
  }

  typedef boost::shared_ptr< ::rave_experimental::PutCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rave_experimental::PutCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct PutCommand
typedef  ::rave_experimental::PutCommand_<std::allocator<void> > PutCommand;

typedef boost::shared_ptr< ::rave_experimental::PutCommand> PutCommandPtr;
typedef boost::shared_ptr< ::rave_experimental::PutCommand const> PutCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rave_experimental::PutCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rave_experimental::PutCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rave_experimental

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::rave_experimental::PutCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f555af83d35595cf42f4aeb704d9cd78";
  }

  static const char* value(const  ::rave_experimental::PutCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf555af83d35595cfULL;
  static const uint64_t static_value2 = 0x42f4aeb704d9cd78ULL;
};

template<class ContainerAllocator>
struct DataType< ::rave_experimental::PutCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rave_experimental/PutCommand";
  }

  static const char* value(const  ::rave_experimental::PutCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rave_experimental::PutCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string object_id\n\
float32 x_offset\n\
float32 y_offset\n\
float32 z_offset\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
bool release\n\
\n\
";
  }

  static const char* value(const  ::rave_experimental::PutCommand_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rave_experimental::PutCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_id);
    stream.next(m.x_offset);
    stream.next(m.y_offset);
    stream.next(m.z_offset);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.release);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PutCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rave_experimental::PutCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rave_experimental::PutCommand_<ContainerAllocator> & v) 
  {
    s << indent << "object_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_id);
    s << indent << "x_offset: ";
    Printer<float>::stream(s, indent + "  ", v.x_offset);
    s << indent << "y_offset: ";
    Printer<float>::stream(s, indent + "  ", v.y_offset);
    s << indent << "z_offset: ";
    Printer<float>::stream(s, indent + "  ", v.z_offset);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "release: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.release);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVE_EXPERIMENTAL_MESSAGE_PUTCOMMAND_H

