/* Auto-generated by genmsg_cpp for file /home/sam/rave_experimental/msg/Update.msg */
#ifndef RAVE_EXPERIMENTAL_MESSAGE_UPDATE_H
#define RAVE_EXPERIMENTAL_MESSAGE_UPDATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace rave_experimental
{
template <class ContainerAllocator>
struct Update_ : public ros::Message
{
  typedef Update_<ContainerAllocator> Type;

  Update_()
  : object_id()
  , xml_file()
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , grab(false)
  {
  }

  Update_(const ContainerAllocator& _alloc)
  : object_id(_alloc)
  , xml_file(_alloc)
  , x(0.0)
  , y(0.0)
  , z(0.0)
  , grab(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  object_id;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _xml_file_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  xml_file;

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef uint8_t _grab_type;
  uint8_t grab;


private:
  static const char* __s_getDataType_() { return "rave_experimental/Update"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2cc603712d0fb9a75a2efdbd218b3c80"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string object_id\n\
string xml_file\n\
float32 x\n\
float32 y\n\
float32 z\n\
bool grab\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, object_id);
    ros::serialization::serialize(stream, xml_file);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, z);
    ros::serialization::serialize(stream, grab);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, object_id);
    ros::serialization::deserialize(stream, xml_file);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, z);
    ros::serialization::deserialize(stream, grab);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(object_id);
    size += ros::serialization::serializationLength(xml_file);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(z);
    size += ros::serialization::serializationLength(grab);
    return size;
  }

  typedef boost::shared_ptr< ::rave_experimental::Update_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rave_experimental::Update_<ContainerAllocator>  const> ConstPtr;
}; // struct Update
typedef  ::rave_experimental::Update_<std::allocator<void> > Update;

typedef boost::shared_ptr< ::rave_experimental::Update> UpdatePtr;
typedef boost::shared_ptr< ::rave_experimental::Update const> UpdateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rave_experimental::Update_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rave_experimental::Update_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rave_experimental

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::rave_experimental::Update_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2cc603712d0fb9a75a2efdbd218b3c80";
  }

  static const char* value(const  ::rave_experimental::Update_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2cc603712d0fb9a7ULL;
  static const uint64_t static_value2 = 0x5a2efdbd218b3c80ULL;
};

template<class ContainerAllocator>
struct DataType< ::rave_experimental::Update_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rave_experimental/Update";
  }

  static const char* value(const  ::rave_experimental::Update_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rave_experimental::Update_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string object_id\n\
string xml_file\n\
float32 x\n\
float32 y\n\
float32 z\n\
bool grab\n\
\n\
";
  }

  static const char* value(const  ::rave_experimental::Update_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rave_experimental::Update_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_id);
    stream.next(m.xml_file);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.grab);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Update_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rave_experimental::Update_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rave_experimental::Update_<ContainerAllocator> & v) 
  {
    s << indent << "object_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_id);
    s << indent << "xml_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.xml_file);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "grab: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grab);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RAVE_EXPERIMENTAL_MESSAGE_UPDATE_H

