/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dave/ros/clam/src/dynamixel_hardware_interface/srv/SetComplianceSlope.srv
 *
 */


#ifndef DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETCOMPLIANCESLOPEREQUEST_H
#define DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETCOMPLIANCESLOPEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_hardware_interface
{
template <class ContainerAllocator>
struct SetComplianceSlopeRequest_
{
  typedef SetComplianceSlopeRequest_<ContainerAllocator> Type;

  SetComplianceSlopeRequest_()
    : slope(0)  {
    }
  SetComplianceSlopeRequest_(const ContainerAllocator& _alloc)
    : slope(0)  {
    }



   typedef uint8_t _slope_type;
  _slope_type slope;


    enum { STEP1 = 2 };
     enum { STEP2 = 4 };
     enum { STEP3 = 8 };
     enum { STEP4 = 16 };
     enum { STEP5 = 32 };
     enum { STEP6 = 64 };
     enum { STEP7 = 128 };
 

  typedef boost::shared_ptr< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SetComplianceSlopeRequest_

typedef ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<std::allocator<void> > SetComplianceSlopeRequest;

typedef boost::shared_ptr< ::dynamixel_hardware_interface::SetComplianceSlopeRequest > SetComplianceSlopeRequestPtr;
typedef boost::shared_ptr< ::dynamixel_hardware_interface::SetComplianceSlopeRequest const> SetComplianceSlopeRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamixel_hardware_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dynamixel_hardware_interface': ['/home/dave/ros/clam/src/dynamixel_hardware_interface/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b6e2b46581dcc882c5d33af6ce19762";
  }

  static const char* value(const ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b6e2b46581dcc88ULL;
  static const uint64_t static_value2 = 0x2c5d33af6ce19762ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_hardware_interface/SetComplianceSlopeRequest";
  }

  static const char* value(const ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STEP1=2\n\
uint8 STEP2=4\n\
uint8 STEP3=8\n\
uint8 STEP4=16\n\
uint8 STEP5=32\n\
uint8 STEP6=64\n\
uint8 STEP7=128\n\
\n\
\n\
uint8 slope\n\
\n\
\n\
";
  }

  static const char* value(const ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.slope);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetComplianceSlopeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_hardware_interface::SetComplianceSlopeRequest_<ContainerAllocator>& v)
  {
    s << indent << "slope: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.slope);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETCOMPLIANCESLOPEREQUEST_H
