/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/dave/ros/clam/src/dynamixel_hardware_interface/srv/SetTorqueLimit.srv
 *
 */


#ifndef DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETTORQUELIMIT_H
#define DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETTORQUELIMIT_H

#include <ros/service_traits.h>


#include <dynamixel_hardware_interface/SetTorqueLimitRequest.h>
#include <dynamixel_hardware_interface/SetTorqueLimitResponse.h>


namespace dynamixel_hardware_interface
{

struct SetTorqueLimit
{

typedef SetTorqueLimitRequest Request;
typedef SetTorqueLimitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTorqueLimit
} // namespace dynamixel_hardware_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimit > {
  static const char* value()
  {
    return "7ac67170532bb79d95db2a425915bbd6";
  }

  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimit&) { return value(); }
};

template<>
struct DataType< ::dynamixel_hardware_interface::SetTorqueLimit > {
  static const char* value()
  {
    return "dynamixel_hardware_interface/SetTorqueLimit";
  }

  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimit&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimitRequest> should match 
// service_traits::MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimit > 
template<>
struct MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimit >::value();
  }
  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_hardware_interface::SetTorqueLimitRequest> should match 
// service_traits::DataType< ::dynamixel_hardware_interface::SetTorqueLimit > 
template<>
struct DataType< ::dynamixel_hardware_interface::SetTorqueLimitRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_hardware_interface::SetTorqueLimit >::value();
  }
  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimitResponse> should match 
// service_traits::MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimit > 
template<>
struct MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_hardware_interface::SetTorqueLimit >::value();
  }
  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_hardware_interface::SetTorqueLimitResponse> should match 
// service_traits::DataType< ::dynamixel_hardware_interface::SetTorqueLimit > 
template<>
struct DataType< ::dynamixel_hardware_interface::SetTorqueLimitResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_hardware_interface::SetTorqueLimit >::value();
  }
  static const char* value(const ::dynamixel_hardware_interface::SetTorqueLimitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_HARDWARE_INTERFACE_MESSAGE_SETTORQUELIMIT_H
