/* #undef FLEXIPORT_EXPORTS */

#define FLEXIPORT_INCLUDE_SERIAL 1
#define FLEXIPORT_INCLUDE_TCP 1
#define FLEXIPORT_INCLUDE_UDP 1
#define FLEXIPORT_INCLUDE_LOGGING 1
#define FLEXIPORT_HAVE_GETADDRINFO 1
