arm:
  kinematics_solver: kdlc_kinematics_plugin/KDLCKinematicsPlugin
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: clam_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 5.0